### ISSUE TITLE
When I run gaffer.bat on windows

### ISSUE THREAD

**Issue by rafaeltambraico** [hypothetical-inc/gaffer#23]
I do not know what it means, I am not a programmer but I would like just testing gaffer. 
Maybe I should copy it to another folder. 

ERROR : startup/gui/menus.py : Error loading Appleseed module - "DLL load failed: The specified module can not be found.".
 Traceback (most recent call last):
  File "C:\gaffer-0.57.3.2-windows\startup\gui\menus.py", line 233, in <module>
    import GafferAppleseed
  File "C:\gaffer-0.57.3.2-windows\python\GafferAppleseed\__init__.py", line 39, in <module>
    from ._GafferAppleseed import *
ImportError: DLL load failed: No se puede encontrar el m¾dulo especificado.

**Comment by ericmehl** [comment]
Hi @rafaeltambraico,
That error won't cause any problems really, it just indicates it is failing to load Appleseed. Appleseed isn't working on the Windows build currently - it's a known problem typically I comment the Appleseed lines out of the startup file so it doesn't give that error. 

You can unzip the attached gaffer.bat file into your `bin` directory and the error should go away (you can overwrite the old one).

[gaffer.zip](https://github.com/hypothetical-inc/gaffer/files/5269312/gaffer.zip)
