### ISSUE TITLE
Gaffer doesn't start

### ISSUE THREAD

**Issue by Chadt54** [hypothetical-inc/gaffer#28]
When I run the gaffer.bat file, I get this message and gaffer doesn't start:

```
C:\Users\Chad>J:\Downloads\gaffer-0.59.4.0-windows\bin\gaffer.bat
Traceback (most recent call last):
  File "J:\Downloads\gaffer-0.59.4.0-windows\bin\../bin/__gaffer.py", line 165, in <module>
    app = loadApp( appName )
  File "J:\Downloads\gaffer-0.59.4.0-windows\bin\../bin/__gaffer.py", line 74, in loadApp
    return appLoader.load( appName )()
  File "J:\Downloads\gaffer-0.59.4.0-windows\python\IECore\ClassLoader.py", line 172, in load
    module = imp.load_module( moduleName, fileForLoad, fileName, ( ".py", "r", imp.PY_SOURCE ) )
  File "J:\Downloads\gaffer-0.59.4.0-windows\bin\..\apps\gui\gui-1.py", line 45, in <module>
    import GafferUI
  File "J:\Downloads\gaffer-0.59.4.0-windows\python\GafferUI\__init__.py", line 125, in <module>
    from ._GafferUI import *
ImportError: DLL load failed: The specified procedure could not be found.
"Error(s) running Gaffer"

C:\Users\Chad>
```

**Comment by ericmehl** [comment]
Hi Chad,
Are you able to start an earlier version of Gaffer on Windows? Try out the [0.59.0.0 beta](https://github.com/hypothetical-inc/gaffer/releases/tag/0.59.0.0) if you haven't already and see if that works.

I made quite a few updates to the dependencies in 0.59.4.0 something may have come apart for certain system configurations.

If that works, I'm guessing it's some mixup between your system's installed libraries and those Gaffer expects to find. Python needs all of the modules it loads to be of the same bit-ness (x32 or x64) and compiler version, etc. so it may be loading a system library that is incompatible with Gaffer's libraries.

If you're up for troubleshooting it with me, download Dependency Walker here: https://www.dependencywalker.com/. It just unzips so you don't need admin privileges to use it.

Then run the following command from your Gaffer `bin` directory, substituting the location where you unzipped `depends22_x64.zip`:
`gaffer env "<directory where you unzipped depends>\depends.exe" /od:dependencies.dwi ..\python\GafferUI\_GafferUI.pyd`

That will save out all of the DLLs that Gaffer loads and I've found it helpful in the past for sorting these problems out. You can view the output file from the GUI depends program to see if there are any obvious errors, or feel free to send it to me and I can look through it: eric at thinkhypothetical.com if you don't want to post it here. I don't think there's anything potentially sensitive but if you're not comfortable with sending or posting it here then I can walk you through analyzing it if you need.

**Comment by Chadt54** [comment]
I tried the 0.59.0.0 beta version and it resulted in the same thing. I'm a little busy lately, so let me get back to you on this. I'll try to run that dependency walker as you described sometime in the next few days. Thanks!
