### ISSUE TITLE
 Gaffer execute command fails on windows blade (in hypervisor) without a GPU - openGL related

### ISSUE THREAD

**Issue by darkcosmoscreative** [hypothetical-inc/gaffer#40]
**Version**: Gaffer 0.60.7.0-windows
**Third-party tools:** Arnold, Deadline

### Description ###

Gaffer execute command fails on windows blade (in hypervisor) without a GPU - openGL related?

### Steps to reproduce ###

1. Run the following type of command on a windows instance with no GPU and the microsoft basic display adapter for drivers.
2. "C:\gaffer-0.60.7.0\bin\gaffer.bat" execute -script "C:\path\to\script.gfr" -nodes ArnoldRender_L010 -frames 1001-1001 -context "-dispatcher:jobDirectory" "'C:\\\path\\\to\\\deadline\\\000001'" "-dispatcher:scriptFileName" "'C:\\\path\\\to\\\deadline\\\000001\\\script.gfr'"
3. (Fwiw, this works without issue if the windows farm blade has a physical GPU.)

### Stack trace ###

<details>
<summary>Stack trace</summary><p>

```
C:\Users\render>C:\gaffer-0.60.7.0\bin\gaffer.bat
ERROR : startup/gui/menus.py : Error loading Arnold module - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\startup\gui\menus.py", line 116, in <module>
    import GafferArnold
  File "C:\gaffer-0.60.7.0\python\GafferArnold\__init__.py", line 59, in <module>
    __import__( "IECoreArnold" )
  File "C:\gaffer-0.60.7.0\python\IECoreArnold\__init__.py", line 37, in <module>
    from ._IECoreArnold import *
ImportError: DLL load failed: The specified module could not be found.

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 263, in resizeEvent
    owner._makeCurrent()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling
Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\Widget.py", line 963, in eventFilter
    return self.__enter( qObject, qEvent )
  File "C:\gaffer-0.60.7.0\python\GafferUI\Widget.py", line 1130, in __enter
    return widget._enterSignal( widget )
IECore.Exception: Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\Gaffer\WeakMethod.py", line 65, in __call__
    return self.__method( s, *args, **kwArgs )
  File "C:\gaffer-0.60.7.0\python\GafferUI\GadgetWidget.py", line 149, in __enter
    if not self._makeCurrent() :
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\GafferUI\Widget.py", line 963, in eventFilter
    return self.__enter( qObject, qEvent )
  File "C:\gaffer-0.60.7.0\python\GafferUI\Widget.py", line 1130, in __enter
    return widget._enterSignal( widget )
IECore.Exception: Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\gaffer-0.60.7.0\python\Gaffer\WeakMethod.py", line 65, in __call__
    return self.__method( s, *args, **kwArgs )
  File "C:\gaffer-0.60.7.0\python\GafferUI\GadgetWidget.py", line 149, in __enter
    if not self._makeCurrent() :
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 183, in _makeCurrent
    return self.__framebufferValid()
  File "C:\gaffer-0.60.7.0\python\GafferUI\GLWidget.py", line 188, in __framebufferValid
    return GL.framebufferobjects.glCheckFramebufferStatus( GL.framebufferobjects.GL_FRAMEBUFFER ) == GL.framebufferobjects.GL_FRAMEBUFFER_COMPLETE
  File "C:\gaffer-0.60.7.0\python\OpenGL\latebind.py", line 44, in __call__
    self._finalCall = self.finalise()
  File "C:\gaffer-0.60.7.0\python\OpenGL\extensions.py", line 245, in finalise
    self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined alternate function (glCheckFramebufferStatus, glCheckFramebufferStatusEXT), check for bool(glCheckFramebufferStatus) before calling

Vertex shader for simpleShaderProg (MainVertexShader & PositionOnlyVertexShader) failed to compile
Fragment shader for simpleShaderProg (MainFragmentShader & ShockingPinkSrcFragmentShader) failed to compile
QGLShaderProgram: shader programs are not supported
Errors linking simple shader:
Vertex shader for blitShaderProg (MainWithTexCoordsVertexShader & UntransformedPositionVertexShader) failed to compile
Fragment shader for blitShaderProg (MainFragmentShader & ImageSrcFragmentShader) failed to compile
QGLShaderProgram: shader programs are not supported
Errors linking blit shader:
"Error(s) running Gaffer"
```
</p>
</details>

**Comment by darkcosmoscreative** [comment]
Hello!

Installing Mesa3d as a troubleshooting step seems to have resolved the issue.

Thanks very much,
Jeremy

**Comment by ericmehl** [comment]
Sorry for the slow reply Jeremy, glad you got it sorted! Mesa was going to be one of my suggestions, so if you're ok with that solution it may be the best.

Gaffer will need some kind of OpenGL implementation for running GL operations, so either a graphics card provided one or software like Mesa.

Doing a normal Arnold render shouldn't require OpenGL though, so there may be some wires that are crossed in the Windows Gaffer build.

If that's the case, it should come to light as I get more of the automated testing in place. I believe the Github cloud machines that run tests don't have any OpenGL capability so hopefully that will reveal any problems.

Feel free to reopen this issue or start a new one if the Mesa solution becomes infeasible and I can help sort it out.
